[package]
name = "cargo-consolidate"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.15"
structopt = "0.3"
toml_edit = "0.22"
camino = "1"
log = "0.4"
env_logger = "0.10"
clap = { version = "4.1", features = ["derive"] }
anyhow = "1.0"
